# Application metadata
name: "Documentation"
app_id: "yeti-documentation"
customer_id: "yeti"
route_prefix: "/documentation"
version: "1.0.0"
description: "Yeti's documentation, powered by mdBook"

static_files:
  path: web
  notFound: 404.html
