# Application metadata
name: "Documentation"
app_id: "documentation"
version: "1.0.0"
description: "Yeti's documentation, powered by docusaurus"

static_files:
  path: web
  route: /
  index: index.html
  build:
    sourceDir: source
    command: mdbook build
