//! documentation — Phase 48 static-crate entry point.
//!
//! Generated by scripts/migrate_app_to_static.py. The `#[path]` mod
//! declarations let the cargo build reach the existing modules/ and
//! resources/ files without moving them — both the dylib path
//! (yeti-compiler flat-src copy) and the static path (this crate)
//! share source during the migration window. Slice 5 retires the
//! dylib path; a follow-up commit then moves modules/ → src/ and
//! drops the `#[path]` attrs.

use yeti_sdk::extensions::{RegistrationContext, Service};
use yeti_sdk::prelude::*;

/// Factory invoked by the customer deployment binary.
pub fn service() -> Box<dyn Service> {
    Box::new(DocumentationService)
}

struct DocumentationService;

impl Service for DocumentationService {
    fn id(&self) -> &'static str {
        "documentation"
    }

    fn name(&self) -> &'static str {
        "Documentation"
    }

    fn is_extension(&self) -> bool {
        false
    }

    fn config_yaml(&self) -> Option<&'static str> {
        Some(include_str!("../config.yaml"))
    }

    fn schemas(&self) -> Vec<&'static str> {
        vec![]
    }

    fn resources(&self, ctx: &mut RegistrationContext) -> yeti_sdk::error::Result<()> {
        // No resources detected — edit this file to add them.
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn factory_returns_configured_service() {
        let svc = service();
        assert_eq!(svc.id(), "documentation");
    }

    #[test]
    fn factory_satisfies_server_builder_bounds() {
        fn assert_factory_bounds<F>(_: F)
        where
            F: Fn() -> Box<dyn Service> + Send + Sync + 'static,
        {
        }
        assert_factory_bounds(service);
    }
}
